"""backend-owned dynamic tile catalog

Revision ID: 20260923_0002
Revises: 20260922_0001
"""
from alembic import op
import sqlalchemy as sa

revision='20260923_0002'
down_revision='20260922_0001'
branch_labels=None
depends_on=None

def upgrade() -> None:
    op.add_column('tile_designs',sa.Column('color',sa.String(7),nullable=False,server_default='#d8d4cb'))
    op.add_column('tile_designs',sa.Column('vein',sa.String(7),nullable=False,server_default='#7e786f'))
    op.add_column('tile_designs',sa.Column('size',sa.String(60),nullable=False,server_default='Custom size'))
    op.add_column('tile_designs',sa.Column('normal_path',sa.Text(),nullable=True))
    op.add_column('tile_designs',sa.Column('roughness_path',sa.Text(),nullable=True))
    op.add_column('tile_designs',sa.Column('texture_repeat',sa.Float(),nullable=False,server_default='2.5'))
    op.add_column('tile_designs',sa.Column('sort_order',sa.Integer(),nullable=False,server_default='1000'))
    op.add_column('tile_designs',sa.Column('built_in',sa.Boolean(),nullable=False,server_default=sa.false()))
    table=sa.table('tile_designs',sa.column('code',sa.String),sa.column('name',sa.String),sa.column('family',sa.String),sa.column('finish',sa.String),sa.column('surface',sa.String),sa.column('image_path',sa.Text),sa.column('color',sa.String),sa.column('vein',sa.String),sa.column('size',sa.String),sa.column('normal_path',sa.Text),sa.column('roughness_path',sa.Text),sa.column('texture_repeat',sa.Float),sa.column('sort_order',sa.Integer),sa.column('built_in',sa.Boolean))
    op.bulk_insert(table,[
        {'code':'AT-2048','name':'Ivory Dune','family':'Stone','finish':'Matt','surface':'Floor','image_path':'/catalog/interior_tiles.jpg','color':'#e7d9c2','vein':'#bbaa90','size':'600 x 1200 mm','normal_path':'/catalog/interior_tiles_nor_gl_1k.jpg','roughness_path':'/catalog/interior_tiles_rough_1k.jpg','texture_repeat':2.8,'sort_order':0,'built_in':True},
        {'code':'AT-2049','name':'Calacatta Gold','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/marble_01.jpg','color':'#f8f5ed','vein':'#b6a071','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':1,'built_in':True},
        {'code':'AT-2050','name':'Statuario White','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/floor_tiles_02.jpg','color':'#f5f5f1','vein':'#898f93','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':2,'built_in':True},
        {'code':'AT-2051','name':'Sage Terrazzo','family':'Terrazzo','finish':'Matt','surface':'Floor','image_path':'/catalog/old_mosaic_floor.jpg','color':'#c2cdc0','vein':'#4f7162','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':3,'built_in':True},
        {'code':'AT-2052','name':'Travertine Sand','family':'Stone','finish':'Matt','surface':'Floor','image_path':'/catalog/floor_tiles_04.jpg','color':'#d6c5aa','vein':'#a28e72','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':4,'built_in':True},
        {'code':'AT-2053','name':'Honey Oak','family':'Wood','finish':'Textured','surface':'Floor','image_path':'/catalog/wood_floor.jpg','color':'#be9461','vein':'#684829','size':'200 x 1200 mm','normal_path':'/catalog/wood_floor_nor_gl_1k.jpg','roughness_path':'/catalog/wood_floor_rough_1k.jpg','texture_repeat':3,'sort_order':5,'built_in':True},
        {'code':'AT-2054','name':'Onyx Veil','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/granite_tile.jpg','color':'#363b3c','vein':'#b8b3a8','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':6,'built_in':True},
        {'code':'AT-2055','name':'Terracotta Arc','family':'Pattern','finish':'Matt','surface':'Floor','image_path':'/catalog/terracotta_floor_tiles.jpg','color':'#b8755a','vein':'#ecd2b1','size':'600 x 600 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.4,'sort_order':7,'built_in':True},
        {'code':'AT-2056','name':'Arabescato Pearl','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/marble_mosaic_tiles.jpg','color':'#ece6db','vein':'#716b61','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':8,'built_in':True},
        {'code':'AT-2057','name':'Verde Alpi','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/stone_tiles_02.jpg','color':'#385b4d','vein':'#c7cbb1','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':9,'built_in':True},
        {'code':'AT-2058','name':'Rosso Levanto','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/granite_tile_02.jpg','color':'#763f3c','vein':'#ddbbb1','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':10,'built_in':True},
        {'code':'AT-2059','name':'Ocean Quartz','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/square_tiles_03.jpg','color':'#78989c','vein':'#d8e5dd','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':11,'built_in':True},
        {'code':'AT-2060','name':'Mistral Stone','family':'Stone','finish':'Matt','surface':'Floor','image_path':'/catalog/granite_tile_03.jpg','color':'#b9bbb5','vein':'#838780','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':12,'built_in':True},
        {'code':'AT-2061','name':'Limestone Cream','family':'Stone','finish':'Matt','surface':'Floor','image_path':'/catalog/floor_tiles_08.jpg','color':'#eee4cf','vein':'#bcb199','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':13,'built_in':True},
        {'code':'AT-2062','name':'Basalt Ash','family':'Stone','finish':'Matt','surface':'Floor','image_path':'/catalog/slate_floor_03.jpg','color':'#686c69','vein':'#414842','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':14,'built_in':True},
        {'code':'AT-2063','name':'Desert Taupe','family':'Stone','finish':'Matt','surface':'Floor','image_path':'/catalog/stone_floor.jpg','color':'#b6a48c','vein':'#8c7b65','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':15,'built_in':True},
        {'code':'AT-2064','name':'Salt & Pepper','family':'Terrazzo','finish':'Matt','surface':'Floor','image_path':'/catalog/terrazzo_tiles.jpg','color':'#eee9e0','vein':'#525652','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':16,'built_in':True},
        {'code':'AT-2065','name':'Blush Confetti','family':'Terrazzo','finish':'Matt','surface':'Floor','image_path':'/catalog/marble_tiles.jpg','color':'#e6c4b4','vein':'#a1665b','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':17,'built_in':True},
        {'code':'AT-2066','name':'Midnight Aggregate','family':'Terrazzo','finish':'Matt','surface':'Floor','image_path':'/catalog/square_tiles_02.jpg','color':'#384448','vein':'#bec8bd','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':18,'built_in':True},
        {'code':'AT-2067','name':'Citrus Fleck','family':'Terrazzo','finish':'Matt','surface':'Floor','image_path':'/catalog/square_tiles.jpg','color':'#ecdcb3','vein':'#b48b42','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':19,'built_in':True},
        {'code':'AT-2068','name':'Nordic Birch','family':'Wood','finish':'Textured','surface':'Floor','image_path':'/catalog/diagonal_parquet.jpg','color':'#dcc7a7','vein':'#9e815d','size':'200 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':3,'sort_order':20,'built_in':True},
        {'code':'AT-2069','name':'Smoked Walnut','family':'Wood','finish':'Textured','surface':'Floor','image_path':'/catalog/herringbone_parquet.jpg','color':'#745541','vein':'#362b25','size':'200 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':3,'sort_order':21,'built_in':True},
        {'code':'AT-2070','name':'Natural Teak','family':'Wood','finish':'Textured','surface':'Floor','image_path':'/catalog/rectangular_parquet.jpg','color':'#aa7547','vein':'#563d27','size':'200 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':3,'sort_order':22,'built_in':True},
        {'code':'AT-2071','name':'Coastal Ash','family':'Wood','finish':'Textured','surface':'Floor','image_path':'/catalog/old_wood_floor.jpg','color':'#bdb6a6','vein':'#7e7563','size':'200 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':3,'sort_order':23,'built_in':True},
        {'code':'AT-2072','name':'Riviera Blue','family':'Pattern','finish':'Matt','surface':'Floor','image_path':'/catalog/floor_tiles_09.jpg','color':'#6c91a3','vein':'#ede7d7','size':'600 x 600 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.4,'sort_order':24,'built_in':True},
        {'code':'AT-2073','name':'Olive Check','family':'Pattern','finish':'Matt','surface':'Floor','image_path':'/catalog/patterned_slate_tiles.jpg','color':'#7e8c6b','vein':'#eee5cc','size':'600 x 600 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.4,'sort_order':25,'built_in':True},
        {'code':'AT-2074','name':'Noir Geometry','family':'Pattern','finish':'Matt','surface':'Floor','image_path':'/catalog/floor_tiles_06.jpg','color':'#353b3b','vein':'#e7e4d8','size':'600 x 600 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.4,'sort_order':26,'built_in':True},
        {'code':'AT-2075','name':'Rose Mosaic','family':'Pattern','finish':'Matt','surface':'Floor','image_path':'/catalog/stone_tiles.jpg','color':'#b6857b','vein':'#eadad0','size':'600 x 600 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.4,'sort_order':27,'built_in':True},
        {'code':'AT-2076','name':'Silver Mist','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/mixed_stone_tiles.jpg','color':'#c8cdce','vein':'#7c8589','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':28,'built_in':True},
        {'code':'AT-2077','name':'Botticino Silk','family':'Marble','finish':'Polished','surface':'Floor','image_path':'/catalog/stone_tiles_03.jpg','color':'#e1cdb1','vein':'#b39b7f','size':'600 x 1200 mm','normal_path':None,'roughness_path':None,'texture_repeat':2.8,'sort_order':29,'built_in':True},
        {'code':'MJP-W-1001','name':'Interior Ceramic Wall','family':'Stone','finish':'Texture reference','surface':'Wall','image_path':'/catalog/interior_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':100,'built_in':True},
        {'code':'MJP-W-1002','name':'Marble Mosaic Wall','family':'Marble','finish':'Texture reference','surface':'Wall','image_path':'/catalog/marble_mosaic_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':101,'built_in':True},
        {'code':'MJP-W-1003','name':'Classic Marble Wall','family':'Marble','finish':'Texture reference','surface':'Wall','image_path':'/catalog/marble_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':102,'built_in':True},
        {'code':'MJP-W-1004','name':'Square Ceramic Wall','family':'Pattern','finish':'Texture reference','surface':'Wall','image_path':'/catalog/square_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':103,'built_in':True},
        {'code':'MJP-W-1005','name':'Square Ceramic II Wall','family':'Pattern','finish':'Texture reference','surface':'Wall','image_path':'/catalog/square_tiles_02.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':104,'built_in':True},
        {'code':'MJP-W-1006','name':'Square Ceramic III Wall','family':'Pattern','finish':'Texture reference','surface':'Wall','image_path':'/catalog/square_tiles_03.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':105,'built_in':True},
        {'code':'MJP-W-1007','name':'Natural Stone Wall','family':'Stone','finish':'Texture reference','surface':'Wall','image_path':'/catalog/stone_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':106,'built_in':True},
        {'code':'MJP-W-1008','name':'Natural Stone II Wall','family':'Stone','finish':'Texture reference','surface':'Wall','image_path':'/catalog/stone_tiles_02.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':107,'built_in':True},
        {'code':'MJP-W-1009','name':'Natural Stone III Wall','family':'Stone','finish':'Texture reference','surface':'Wall','image_path':'/catalog/stone_tiles_03.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':108,'built_in':True},
        {'code':'MJP-W-1010','name':'Mixed Stone Wall','family':'Stone','finish':'Texture reference','surface':'Wall','image_path':'/catalog/mixed_stone_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':109,'built_in':True},
        {'code':'MJP-W-1011','name':'Terrazzo Wall','family':'Terrazzo','finish':'Texture reference','surface':'Wall','image_path':'/catalog/terrazzo_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':110,'built_in':True},
        {'code':'MJP-W-1012','name':'Terracotta Wall','family':'Pattern','finish':'Texture reference','surface':'Wall','image_path':'/catalog/terracotta_floor_tiles.jpg','color':'#ffffff','vein':'#8c8377','size':'Confirm with supplier','normal_path':None,'roughness_path':None,'texture_repeat':2.5,'sort_order':111,'built_in':True},
    ])

def downgrade() -> None:
    op.execute("DELETE FROM tile_designs WHERE built_in = true")
    for name in ['built_in','sort_order','texture_repeat','roughness_path','normal_path','size','vein','color']:
        op.drop_column('tile_designs',name)

