import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { createServer } from 'vite'

await mkdir('test-results', {recursive:true})
const server=await createServer({server:{host:'127.0.0.1',port:0,strictPort:false}})
await server.listen()
const testUrl=server.resolvedUrls.local[0]
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']})
const page=await browser.newPage({viewport:{width:1440,height:1050}})
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('net::ERR'))errors.push(message.text())})
try {
  await page.goto(testUrl,{waitUntil:'networkidle'})
  await page.getByRole('button',{name:'STEP INSIDE',exact:true}).waitFor({timeout:30000})
  assert.equal(await page.locator('.graphics-error').count(),0)
  assert.equal(await page.locator('.loading-view').count(),0)
  await page.screenshot({path:'test-results/desktop.png',fullPage:true})
  const initial=await page.locator('.three-host').screenshot()
  await page.mouse.click(1135,340)
  assert.equal(await page.locator('.wall-quickbar').count(),1,'Clicking a 3D wall opens quick colours')
  await page.getByRole('button',{name:'Sage wall colour',exact:true}).click()
  assert.equal(await page.getByRole('button',{name:'Sage wall colour',exact:true}).getAttribute('aria-pressed'),'true')
  assert.ok(!initial.equals(await page.locator('.three-host').screenshot()),'Wall colour updates the rendered house')
  await page.getByRole('button',{name:'Art deco arches',exact:true}).click()
  assert.deepEqual(await page.evaluate(()=>{const styles=JSON.parse(localStorage.getItem('aura-wall-styles'));return [styles[0].color,styles[2].color,styles[2].design]}),['#aa5946','#758872','arches'],'Only the selected wall changes')
  await page.screenshot({path:'test-results/wall-colours.png',fullPage:true})
  await page.getByRole('button',{name:'Close wall colours',exact:true}).click()
  await page.getByRole('button',{name:'COLLECTIONS',exact:true}).click()
  assert.equal(await page.locator('.catalog-card').count(),56)
  await page.getByRole('button',{name:'Wood',exact:true}).click()
  assert.equal(await page.locator('.catalog-card').count(),5)
  await page.getByRole('button',{name:'All',exact:true}).click()
  await page.getByRole('textbox',{name:'Search tile collections'}).fill('verde')
  assert.equal(await page.locator('.catalog-card').count(),1)
  await page.getByRole('button',{name:'Apply Verde Alpi',exact:true}).click()
  await page.getByRole('button',{name:'Save Verde Alpi',exact:true}).click()
  assert.match(await page.locator('.catalog-bottom').innerText(),/Verde Alpi applied/)
  await page.getByRole('textbox',{name:'Search tile collections'}).fill('')
  await page.screenshot({path:'test-results/collections.png',fullPage:true})
  await page.getByRole('button',{name:'Close dialog',exact:true}).click()
  assert.equal(await page.locator('.product-heading h3').innerText(),'Verde Alpi')
  const changed=await page.locator('.three-host').screenshot()
  assert.ok(!initial.equals(changed),'Tile selection changes the rendered scene')
  await page.getByRole('combobox',{name:'Tile application scope',exact:true}).selectOption('room')
  await page.getByRole('button',{name:'Apply Statuario White',exact:true}).click()
  assert.equal(await page.locator('.product-heading h3').innerText(),'Statuario White')
  for(const name of ['Kitchen','Master suite','Bathroom']) {
    await page.locator('.room-nav').getByRole('button',{name:new RegExp(name)}).click()
    assert.match(await page.locator('.scene-status').innerText(),new RegExp(name))
    assert.equal(await page.locator('.product-heading h3').innerText(),'Verde Alpi')
  }
  await page.locator('.room-nav').getByRole('button',{name:/Living room/}).click()
  assert.equal(await page.locator('.product-heading h3').innerText(),'Statuario White')
  await page.getByRole('button',{name:'STEP INSIDE',exact:true}).click()
  await page.evaluate(()=>document.exitPointerLock())
  await page.locator('canvas').focus()
  const beforeMove=await page.locator('.floorplan g').getAttribute('transform')
  await page.keyboard.down('w');await page.waitForTimeout(800);await page.keyboard.up('w')
  const afterMove=await page.locator('.floorplan g').getAttribute('transform')
  assert.notEqual(beforeMove,afterMove,'W moves the camera')
  await page.screenshot({path:'test-results/walkthrough.png',fullPage:true})
  await page.getByRole('button',{name:'VR mode',exact:true}).click()
  await page.getByRole('button',{name:/Stereo preview Two eye/}).click()
  assert.equal(await page.locator('.stereo-divider').count(),1)
  await page.screenshot({path:'test-results/stereo.png'})
  await page.getByRole('button',{name:'Normal view',exact:true}).click()
  await page.getByRole('button',{name:'VR mode',exact:true}).click()
  await page.getByRole('button',{name:/Enter headset VR WebXR/}).click()
  await page.getByRole('status').filter({hasText:/No compatible VR headset|Headset VR needs|VR could not start/}).waitFor()
  await page.getByRole('button',{name:/Saved tiles, 1/}).click()
  assert.equal(await page.locator('.catalog-card').count(),1)
  await page.getByRole('button',{name:'Close dialog',exact:true}).click()
  // Check the actual navigation mesh against every room and a grid flood fill.
  const navigation=await page.evaluate(async()=>{
    const THREE=await import('/node_modules/three/build/three.module.js')
    const {buildHouse,viewpoints,roomAt}=await import('/src/house.ts')
    const renderer=new THREE.WebGLRenderer();const house=buildHouse(renderer)
    const starts=viewpoints.map(p=>house.canStand(p.x,p.z))
    const todo=[[-1.75,6.75]];const seen=new Set();const rooms=new Set()
    while(todo.length){const [x,z]=todo.pop();const key=`${x},${z}`;if(seen.has(key)||!house.canStand(x,z))continue;seen.add(key);rooms.add(roomAt(x,z));for(const [dx,dz] of [[.25,0],[-.25,0],[0,.25],[0,-.25]])todo.push([x+dx,z+dz])}
    const solidWall=!house.canStand(0,0),door=house.canStand(0,4.5)
    house.dispose();renderer.dispose();return{starts,rooms:[...rooms].sort(),solidWall,door}
  })
  assert.deepEqual(navigation.starts,[true,true,true,true],'Every room viewpoint is clear')
  assert.deepEqual(navigation.rooms,[0,1,2,3],'All four rooms are reachable through open doorways')
  assert.ok(navigation.solidWall&&navigation.door,'Walls block movement and doorways permit movement')
  await page.setViewportSize({width:390,height:844})
  await page.locator('.room-nav').getByRole('button',{name:/Kitchen/}).click()
  await page.screenshot({path:'test-results/mobile.png',fullPage:true})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow')
  await page.getByRole('button',{name:'Customise wall colours',exact:true}).click()
  assert.equal(await page.locator('.wall-finishes .finish-option').count(),20,'Wall studio offers 20 finishes including wall tiles')
  await page.getByRole('button',{name:'Limewash',exact:true}).click()
  await page.screenshot({path:'test-results/mobile-wall-studio.png',fullPage:true})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Wall studio fits on mobile')
  await page.getByRole('button',{name:'Close wall colour studio',exact:true}).click()
  const startTouch=await page.locator('.floorplan g').getAttribute('transform')
  const forward=await page.getByRole('button',{name:'Walk forward',exact:true}).boundingBox()
  await page.mouse.move(forward.x+forward.width/2,forward.y+forward.height/2);await page.mouse.down();await page.waitForTimeout(650);await page.mouse.up()
  assert.notEqual(await page.locator('.floorplan g').getAttribute('transform'),startTouch,'On-screen movement works')
  await page.getByRole('button',{name:'Toggle navigation',exact:true}).click()
  await page.getByRole('button',{name:'COLLECTIONS',exact:true}).click()
  await page.screenshot({path:'test-results/mobile-collections.png',fullPage:true})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  assert.deepEqual(errors,[],'No JavaScript or WebGL errors')
  console.log('PASS: 56 surfaces, per-wall click/colour/design, filters/search, favorites, room-specific PBR materials, rendered updates, connected interiors, wall collisions, keyboard/touch movement, stereo, unsupported VR fallback, mobile layout. Screenshots: test-results/')
} finally {await browser.close();await server.close()}
