import { type Tile } from './catalog';

export const fallbackTiles: Tile[] = [
  {
    "id": "AT-2048",
    "name": "Ivory Dune",
    "family": "Stone",
    "color": "#e7d9c2",
    "vein": "#bbaa90",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/interior_tiles.jpg",
    "normal": "http://localhost:8000/catalog/interior_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/interior_tiles_rough_1k.jpg",
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 0
  },
  {
    "id": "AT-2049",
    "name": "Calacatta Gold",
    "family": "Marble",
    "color": "#f8f5ed",
    "vein": "#b6a071",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/marble_01.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 1
  },
  {
    "id": "AT-2050",
    "name": "Statuario White",
    "family": "Marble",
    "color": "#f5f5f1",
    "vein": "#898f93",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/floor_tiles_02.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 2
  },
  {
    "id": "AT-2051",
    "name": "Sage Terrazzo",
    "family": "Terrazzo",
    "color": "#c2cdc0",
    "vein": "#4f7162",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/old_mosaic_floor.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 3
  },
  {
    "id": "AT-2052",
    "name": "Travertine Sand",
    "family": "Stone",
    "color": "#d6c5aa",
    "vein": "#a28e72",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/floor_tiles_04.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 4
  },
  {
    "id": "AT-2053",
    "name": "Honey Oak",
    "family": "Wood",
    "color": "#be9461",
    "vein": "#684829",
    "finish": "Textured",
    "size": "200 x 1200 mm",
    "image": "http://localhost:8000/catalog/wood_floor.jpg",
    "normal": "http://localhost:8000/catalog/wood_floor_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/wood_floor_rough_1k.jpg",
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 5
  },
  {
    "id": "AT-2054",
    "name": "Onyx Veil",
    "family": "Marble",
    "color": "#363b3c",
    "vein": "#b8b3a8",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/granite_tile.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 6
  },
  {
    "id": "AT-2055",
    "name": "Terracotta Arc",
    "family": "Pattern",
    "color": "#b8755a",
    "vein": "#ecd2b1",
    "finish": "Matt",
    "size": "600 x 600 mm",
    "image": "http://localhost:8000/catalog/terracotta_floor_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.4,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 7
  },
  {
    "id": "AT-2056",
    "name": "Arabescato Pearl",
    "family": "Marble",
    "color": "#ece6db",
    "vein": "#716b61",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/marble_mosaic_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 8
  },
  {
    "id": "AT-2057",
    "name": "Verde Alpi",
    "family": "Marble",
    "color": "#385b4d",
    "vein": "#c7cbb1",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/stone_tiles_02.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 9
  },
  {
    "id": "AT-2058",
    "name": "Rosso Levanto",
    "family": "Marble",
    "color": "#763f3c",
    "vein": "#ddbbb1",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/granite_tile_02.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 10
  },
  {
    "id": "AT-2059",
    "name": "Ocean Quartz",
    "family": "Marble",
    "color": "#78989c",
    "vein": "#d8e5dd",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/square_tiles_03.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 11
  },
  {
    "id": "AT-2060",
    "name": "Mistral Stone",
    "family": "Stone",
    "color": "#b9bbb5",
    "vein": "#838780",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/granite_tile_03.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 12
  },
  {
    "id": "AT-2061",
    "name": "Limestone Cream",
    "family": "Stone",
    "color": "#eee4cf",
    "vein": "#bcb199",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/floor_tiles_08.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 13
  },
  {
    "id": "AT-2062",
    "name": "Basalt Ash",
    "family": "Stone",
    "color": "#686c69",
    "vein": "#414842",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/slate_floor_03.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 14
  },
  {
    "id": "AT-2063",
    "name": "Desert Taupe",
    "family": "Stone",
    "color": "#b6a48c",
    "vein": "#8c7b65",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/stone_floor.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 15
  },
  {
    "id": "AT-2064",
    "name": "Salt & Pepper",
    "family": "Terrazzo",
    "color": "#eee9e0",
    "vein": "#525652",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/terrazzo_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 16
  },
  {
    "id": "AT-2065",
    "name": "Blush Confetti",
    "family": "Terrazzo",
    "color": "#e6c4b4",
    "vein": "#a1665b",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/marble_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 17
  },
  {
    "id": "AT-2066",
    "name": "Midnight Aggregate",
    "family": "Terrazzo",
    "color": "#384448",
    "vein": "#bec8bd",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/square_tiles_02.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 18
  },
  {
    "id": "AT-2067",
    "name": "Citrus Fleck",
    "family": "Terrazzo",
    "color": "#ecdcb3",
    "vein": "#b48b42",
    "finish": "Matt",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/square_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 19
  },
  {
    "id": "AT-2068",
    "name": "Nordic Birch",
    "family": "Wood",
    "color": "#dcc7a7",
    "vein": "#9e815d",
    "finish": "Textured",
    "size": "200 x 1200 mm",
    "image": "http://localhost:8000/catalog/diagonal_parquet.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 20
  },
  {
    "id": "AT-2069",
    "name": "Smoked Walnut",
    "family": "Wood",
    "color": "#745541",
    "vein": "#362b25",
    "finish": "Textured",
    "size": "200 x 1200 mm",
    "image": "http://localhost:8000/catalog/herringbone_parquet.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 21
  },
  {
    "id": "AT-2070",
    "name": "Natural Teak",
    "family": "Wood",
    "color": "#aa7547",
    "vein": "#563d27",
    "finish": "Textured",
    "size": "200 x 1200 mm",
    "image": "http://localhost:8000/catalog/rectangular_parquet.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 22
  },
  {
    "id": "AT-2071",
    "name": "Coastal Ash",
    "family": "Wood",
    "color": "#bdb6a6",
    "vein": "#7e7563",
    "finish": "Textured",
    "size": "200 x 1200 mm",
    "image": "http://localhost:8000/catalog/old_wood_floor.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 23
  },
  {
    "id": "AT-2072",
    "name": "Riviera Blue",
    "family": "Pattern",
    "color": "#6c91a3",
    "vein": "#ede7d7",
    "finish": "Matt",
    "size": "600 x 600 mm",
    "image": "http://localhost:8000/catalog/floor_tiles_09.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.4,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 24
  },
  {
    "id": "AT-2073",
    "name": "Olive Check",
    "family": "Pattern",
    "color": "#7e8c6b",
    "vein": "#eee5cc",
    "finish": "Matt",
    "size": "600 x 600 mm",
    "image": "http://localhost:8000/catalog/patterned_slate_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.4,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 25
  },
  {
    "id": "AT-2074",
    "name": "Noir Geometry",
    "family": "Pattern",
    "color": "#353b3b",
    "vein": "#e7e4d8",
    "finish": "Matt",
    "size": "600 x 600 mm",
    "image": "http://localhost:8000/catalog/floor_tiles_06.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.4,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 26
  },
  {
    "id": "AT-2075",
    "name": "Rose Mosaic",
    "family": "Pattern",
    "color": "#b6857b",
    "vein": "#eadad0",
    "finish": "Matt",
    "size": "600 x 600 mm",
    "image": "http://localhost:8000/catalog/stone_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.4,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 27
  },
  {
    "id": "AT-2076",
    "name": "Silver Mist",
    "family": "Marble",
    "color": "#c8cdce",
    "vein": "#7c8589",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/mixed_stone_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 28
  },
  {
    "id": "AT-2077",
    "name": "Botticino Silk",
    "family": "Marble",
    "color": "#e1cdb1",
    "vein": "#b39b7f",
    "finish": "Polished",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/stone_tiles_03.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 29
  },
  {
    "id": "MJP-F-2001",
    "name": "Cocoa Ceramic",
    "family": "Stone",
    "color": "#866d59",
    "vein": "#514238",
    "finish": "Satin",
    "size": "600 x 600 mm",
    "image": "http://localhost:8000/catalog/tiled_floor_001_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/tiled_floor_001_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/tiled_floor_001_rough_1k.jpg",
    "repeat": 2.8,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 30
  },
  {
    "id": "MJP-F-2002",
    "name": "Chestnut Courtyard",
    "family": "Pattern",
    "color": "#9c785c",
    "vein": "#614735",
    "finish": "Matt",
    "size": "300 x 300 mm",
    "image": "http://localhost:8000/catalog/brown_floor_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/brown_floor_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/brown_floor_tiles_rough_1k.jpg",
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 31
  },
  {
    "id": "MJP-F-2003",
    "name": "Gripstone Grey",
    "family": "Stone",
    "color": "#787872",
    "vein": "#484943",
    "finish": "Anti-skid",
    "size": "300 x 300 mm",
    "image": "http://localhost:8000/catalog/anti_skid_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/anti_skid_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/anti_skid_tiles_rough_1k.jpg",
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 32
  },
  {
    "id": "MJP-F-2004",
    "name": "Terracotta Patio",
    "family": "Pattern",
    "color": "#a76649",
    "vein": "#633c2d",
    "finish": "Matt",
    "size": "300 x 300 mm",
    "image": "http://localhost:8000/catalog/patio_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/patio_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/patio_tiles_rough_1k.jpg",
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 33
  },
  {
    "id": "MJP-F-2005",
    "name": "Vintage Ivory Tile",
    "family": "Pattern",
    "color": "#c6bba7",
    "vein": "#776e61",
    "finish": "Distressed matt",
    "size": "300 x 300 mm",
    "image": "http://localhost:8000/catalog/worn_tile_floor_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/worn_tile_floor_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/worn_tile_floor_rough_1k.jpg",
    "repeat": 3,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 34
  },
  {
    "id": "MJP-F-2006",
    "name": "Silver Slab",
    "family": "Stone",
    "color": "#aaa9a4",
    "vein": "#656660",
    "finish": "Honed",
    "size": "600 x 1200 mm",
    "image": "http://localhost:8000/catalog/slab_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/slab_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/slab_tiles_rough_1k.jpg",
    "repeat": 2.6,
    "surface": "Floor",
    "builtIn": true,
    "sortOrder": 35
  },
  {
    "id": "MJP-W-1001",
    "name": "Interior Ceramic Wall",
    "family": "Stone",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/interior_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 100
  },
  {
    "id": "MJP-W-1002",
    "name": "Marble Mosaic Wall",
    "family": "Marble",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/marble_mosaic_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 101
  },
  {
    "id": "MJP-W-1003",
    "name": "Classic Marble Wall",
    "family": "Marble",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/marble_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 102
  },
  {
    "id": "MJP-W-1004",
    "name": "Square Ceramic Wall",
    "family": "Pattern",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/square_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 103
  },
  {
    "id": "MJP-W-1005",
    "name": "Square Ceramic II Wall",
    "family": "Pattern",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/square_tiles_02.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 104
  },
  {
    "id": "MJP-W-1006",
    "name": "Square Ceramic III Wall",
    "family": "Pattern",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/square_tiles_03.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 105
  },
  {
    "id": "MJP-W-1007",
    "name": "Natural Stone Wall",
    "family": "Stone",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/stone_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 106
  },
  {
    "id": "MJP-W-1008",
    "name": "Natural Stone II Wall",
    "family": "Stone",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/stone_tiles_02.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 107
  },
  {
    "id": "MJP-W-1009",
    "name": "Natural Stone III Wall",
    "family": "Stone",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/stone_tiles_03.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 108
  },
  {
    "id": "MJP-W-1010",
    "name": "Mixed Stone Wall",
    "family": "Stone",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/mixed_stone_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 109
  },
  {
    "id": "MJP-W-1011",
    "name": "Terrazzo Wall",
    "family": "Terrazzo",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/terrazzo_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 110
  },
  {
    "id": "MJP-W-1012",
    "name": "Terracotta Wall",
    "family": "Pattern",
    "color": "#ffffff",
    "vein": "#8c8377",
    "finish": "Texture reference",
    "size": "Confirm with supplier",
    "image": "http://localhost:8000/catalog/terracotta_floor_tiles.jpg",
    "normal": null,
    "roughness": null,
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 111
  },
  {
    "id": "MJP-W-1013",
    "name": "Pearl Rounded Mosaic",
    "family": "Pattern",
    "color": "#d8d7d2",
    "vein": "#777a78",
    "finish": "Satin relief",
    "size": "100 x 100 mm",
    "image": "http://localhost:8000/catalog/rounded_square_tiled_wall_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/rounded_square_tiled_wall_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/rounded_square_tiled_wall_rough_1k.jpg",
    "repeat": 3.2,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 112
  },
  {
    "id": "MJP-W-1014",
    "name": "Architect White Grid",
    "family": "Pattern",
    "color": "#e2e1dc",
    "vein": "#858782",
    "finish": "Matt relief",
    "size": "100 x 100 mm",
    "image": "http://localhost:8000/catalog/square_tiled_wall_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/square_tiled_wall_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/square_tiled_wall_rough_1k.jpg",
    "repeat": 3.4,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 113
  },
  {
    "id": "MJP-W-1015",
    "name": "Linear Sand Facade",
    "family": "Stone",
    "color": "#b4a893",
    "vein": "#6f675b",
    "finish": "Textured",
    "size": "150 x 600 mm",
    "image": "http://localhost:8000/catalog/rectangular_facade_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/rectangular_facade_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/rectangular_facade_tiles_rough_1k.jpg",
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 114
  },
  {
    "id": "MJP-W-1016",
    "name": "Graphite Linear Facade",
    "family": "Stone",
    "color": "#5d5c58",
    "vein": "#2f302e",
    "finish": "Textured",
    "size": "150 x 600 mm",
    "image": "http://localhost:8000/catalog/rectangular_facade_tiles_02_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/rectangular_facade_tiles_02_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/rectangular_facade_tiles_02_rough_1k.jpg",
    "repeat": 2.5,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 115
  },
  {
    "id": "MJP-W-1017",
    "name": "Ivory Ledger Stone",
    "family": "Stone",
    "color": "#c8bca7",
    "vein": "#817765",
    "finish": "Split face",
    "size": "150 x 600 mm",
    "image": "http://localhost:8000/catalog/stone_tile_wall_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/stone_tile_wall_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/stone_tile_wall_rough_1k.jpg",
    "repeat": 2.2,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 116
  },
  {
    "id": "MJP-W-1018",
    "name": "Volcanic Charcoal",
    "family": "Stone",
    "color": "#4a4945",
    "vein": "#222321",
    "finish": "Natural cleft",
    "size": "300 x 600 mm",
    "image": "http://localhost:8000/catalog/volcanic_rock_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/volcanic_rock_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/volcanic_rock_tiles_rough_1k.jpg",
    "repeat": 2.3,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 117
  },
  {
    "id": "MJP-W-1019",
    "name": "Urban Concrete Panels",
    "family": "Stone",
    "color": "#a7a49d",
    "vein": "#66645f",
    "finish": "Honed",
    "size": "300 x 600 mm",
    "image": "http://localhost:8000/catalog/concrete_tile_facade_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/concrete_tile_facade_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/concrete_tile_facade_rough_1k.jpg",
    "repeat": 2.4,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 118
  },
  {
    "id": "MJP-W-1020",
    "name": "Heritage White Subway",
    "family": "Pattern",
    "color": "#dedbd4",
    "vein": "#8b857d",
    "finish": "Glossy worn",
    "size": "75 x 300 mm",
    "image": "http://localhost:8000/catalog/long_white_tiles_diff_1k.jpg",
    "normal": "http://localhost:8000/catalog/long_white_tiles_nor_gl_1k.jpg",
    "roughness": "http://localhost:8000/catalog/long_white_tiles_rough_1k.jpg",
    "repeat": 3,
    "surface": "Wall",
    "builtIn": true,
    "sortOrder": 119
  }
];