import { useEffect, useRef, useState, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { createPortal } from 'react-dom'
import { ArrowUpRight, Check, ChevronLeft, ChevronRight, Clock3, Expand, Eye, Footprints, Grid2X2, Heart, Home, Mail, MapPin, Menu, MoveRight, Paintbrush, Phone, Search, Share2, Sparkles, Sun, Upload, X } from 'lucide-react'
import { tiles, families, roomNames, sampleUrl, type Family, type SurfaceUse, type Tile } from './catalog'
import { Walkthrough, type ViewHandle } from './Walkthrough'
import { wallDesigns, wallSides, type WallDesign, type WallStyle } from './house'
import { articles } from './journal'
import { fetchCustomTiles, saveCustomTile } from './api'
import './tailwind.css'
import './styles.css'
import './showroom.css'
import './brand.css'
import './layout-fix.css'

function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  const panel=useRef<HTMLDivElement>(null)
  useEffect(()=>{const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';if(document.pointerLockElement)document.exitPointerLock();panel.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const elements=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, a[href], [tabindex="0"]');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus()}},[])
  return createPortal(<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={panel}><div className="modal-heading"><div><p className="overline">MJP CERAMICS / MATERIAL STUDIO</p><h2>{title}</h2></div><button className="round-button" aria-label="Close dialog" onClick={onClose}><X size={21}/></button></div>{children}</div></div>,document.fullscreenElement??document.body)
}
function initialTiles(){const ids=new URLSearchParams(location.search).get('surfaces')?.split(',');return roomNames.map((_,i)=>tiles.find(t=>t.id===ids?.[i])??tiles[5])}
const defaultWalls=['#aa5946','#33757a','#75566e','#347284']
const paintSwatches=[{name:'Warm clay',color:'#aa5946'},{name:'Linen',color:'#d4bea5'},{name:'Sage',color:'#758872'},{name:'Deep olive',color:'#53624c'},{name:'Sea glass',color:'#33757a'},{name:'Denim',color:'#54728d'},{name:'Dusty rose',color:'#b78382'},{name:'Plum',color:'#75566e'},{name:'Soft white',color:'#e4ddd0'},{name:'Charcoal',color:'#565b59'}]
const finishNames:Record<WallDesign,string>={paint:'Smooth paint',limewash:'Limewash',linen:'Linen texture',stripes:'Fine stripes',arches:'Art deco arches',subway:'Subway tile',herringbone:'Herringbone tile',terrazzo:'Terrazzo fleck',hexagon:'Hexagon tile',zellige:'Zellige tile',kitkat:'KitKat finger tile',travertine:'Travertine slab',marble:'Marble vein',checker:'Checker tile',mosaic:'Mosaic tile',chevron:'Chevron tile',fishscale:'Fish scale tile',concrete:'Concrete finish',fluted:'Fluted wall tile',grid:'Large grid tile'}
function initialWalls():WallStyle[]{
  let previousColours:string[]=[],saved:Partial<WallStyle>[]=[]
  try{const value=JSON.parse(localStorage.getItem('aura-wall-colours')??'[]');if(Array.isArray(value))previousColours=value}catch{/* Use curated defaults. */}
  try{const value=JSON.parse(localStorage.getItem('aura-wall-styles')??'[]');if(Array.isArray(value))saved=value}catch{/* Use curated defaults. */}
  const params=new URLSearchParams(location.search),colours=params.get('walls')?.split(','),designs=params.get('patterns')?.split(',')
  return Array.from({length:16},(_,i)=>{const room=Math.floor(i/4),candidate=colours?.[colours.length===16?i:room]??saved[i]?.color??previousColours[room],pattern=designs?.[i]??saved[i]?.design;return {color:typeof candidate==='string'&&/^#[\da-fA-F]{6}$/.test(candidate)?candidate:defaultWalls[room],design:wallDesigns.includes(pattern as WallDesign)?pattern as WallDesign:'paint'}})
}
function App(){
  const view=useRef<ViewHandle>(null);const [selected,setSelected]=useState(initialTiles);const [room,setRoom]=useState(0);const [walking,setWalking]=useState(false);const [stereo,setStereo]=useState(false);const [xr,setXR]=useState(false);const [ready,setReady]=useState(false)
  const [menu,setMenu]=useState(false);const [modal,setModal]=useState<null|'collections'|'details'|'guide'|'inspiration'|'vr'|'blog'|'upload'>(null);const [articleId,setArticleId]=useState(articles[0].id);const [filter,setFilter]=useState('All');const [query,setQuery]=useState('');const [onlySaved,setOnlySaved]=useState(false);const [scope,setScope]=useState('all');const [brightness,setBrightness]=useState(.95);const [notice,setNotice]=useState('');const [wallStyles,setWallStyles]=useState(initialWalls);const [activeWall,setActiveWall]=useState(0);const [paintOpen,setPaintOpen]=useState(false);const [quickPaint,setQuickPaint]=useState(false);const [customTiles,setCustomTiles]=useState<Tile[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('mjp-custom-tiles')??'[]');return Array.isArray(saved)?saved:[]}catch{return []}});const [uploadImage,setUploadImage]=useState('');const [uploadName,setUploadName]=useState('');const [uploadCode,setUploadCode]=useState('');const [uploadFamily,setUploadFamily]=useState<Family>('Pattern');const [uploadFinish,setUploadFinish]=useState('Matt');const [uploadSurface,setUploadSurface]=useState<SurfaceUse>('Both')
  const [saved,setSaved]=useState<string[]>(()=>{try{const s=JSON.parse(localStorage.getItem('aura-favorites')??'[]');return Array.isArray(s)?s.filter((v:unknown)=>typeof v==='string'):[]}catch{return []}})
  const [applied,setApplied]=useState('');const catalogTiles=[...tiles,...customTiles];const tile=selected[room];const current=catalogTiles.indexOf(tile);const isLiked=saved.includes(tile.id);const article=articles.find(item=>item.id===articleId)??articles[0]
  useEffect(()=>{try{localStorage.setItem('aura-favorites',JSON.stringify(saved))}catch{/* favorites still work for this visit */}},[saved])
  useEffect(()=>{try{localStorage.setItem('aura-wall-styles',JSON.stringify(wallStyles))}catch{/* Wall styles still work for this visit. */}},[wallStyles])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer)},[notice])
  useEffect(()=>{try{localStorage.setItem('mjp-custom-tiles',JSON.stringify(customTiles))}catch{/* Large image previews remain available for this visit. */}},[customTiles])
  useEffect(()=>{void fetchCustomTiles().then(remote=>setCustomTiles(previous=>{const remoteIds=new Set(remote.map(tile=>tile.id));return [...remote,...previous.filter(tile=>!remoteIds.has(tile.id))]})).catch(()=>{/* API is optional until the backend is started. */})},[])
  useEffect(()=>{if(!ready)return;const initial=Number(new URLSearchParams(location.search).get('room'));if(Number.isInteger(initial)&&initial>=0&&initial<4)view.current?.goTo(initial)},[ready])
  const apply=(value:Tile)=>{const target=value.surface;if(target!=='Wall')setSelected(previous=>previous.map((old,i)=>scope==='all'||i===room?value:old));if(value.image&&target!=='Floor')setWallStyles(previous=>previous.map((old,i)=>i===activeWall?{...old,color:'#ffffff',design:'paint',image:value.image}:old));const targetLabel=target==='Wall'?'the selected wall':target==='Both'?'the selected wall and floor':scope==='all'?'the whole house':roomNames[room].toLowerCase();setApplied(`${value.name} applied to ${targetLabel}`)}
  const toggleSave=(id:string)=>setSaved(s=>s.includes(id)?s.filter(item=>item!==id):[...s,id])
  const openCatalog=(favorites=false)=>{setModal('collections');setOnlySaved(favorites);setFilter('All');setQuery('');setMenu(false)}
  const jump=(i:number)=>{view.current?.goTo(i);setRoom(i);setActiveWall(i*4);setQuickPaint(false)}
  const styleWall=(patch:Partial<WallStyle>)=>setWallStyles(previous=>previous.map((old,i)=>i===activeWall?{...old,...patch}:old))
  const useOnWall=(value:Tile)=>{if(!value.image)return;styleWall({color:'#ffffff',design:'paint',image:value.image});setApplied(`${value.name} applied to the selected wall`);setModal(null)}
  const readUpload=(file:File|undefined)=>{if(!file)return;if(!file.type.startsWith('image/'))return setNotice('Please choose a JPG, PNG or WebP texture image.');if(file.size>5*1024*1024)return setNotice('Please use an image below 5 MB for a smooth preview.');const reader=new FileReader();reader.onload=()=>setUploadImage(String(reader.result));reader.readAsDataURL(file)}
  const addDesign=async()=>{const code=uploadCode.trim().toUpperCase();if(!uploadImage||!uploadName.trim()||!code)return setNotice('Add a tile code, design name and texture image first.');if(!/^[A-Z0-9][A-Z0-9-]{2,24}$/.test(code))return setNotice('Use a code like AT-W-1001: letters, numbers and hyphens only.');if(catalogTiles.some(tile=>tile.id.toUpperCase()===code))return setNotice(`${code} already exists. Use a unique tile code.`);const draft:Tile={id:code,name:uploadName.trim(),family:uploadFamily,color:'#d8d4cb',vein:'#7e786f',finish:uploadFinish.trim()||'Matt',size:'Custom size',seed:Date.now()%100000,scan:'',image:uploadImage,surface:uploadSurface};setCustomTiles(previous=>[draft,...previous]);apply(draft);setUploadImage('');setUploadName('');setUploadCode('');setUploadFinish('Matt');setUploadSurface('Both');setModal('collections');try{const design=await saveCustomTile(draft);setCustomTiles(previous=>previous.map(tile=>tile.id===code?design:tile));setNotice(`${design.name} (${code}) saved permanently.`)}catch(error){setNotice(`${draft.name} (${code}) added to this browser. Start the API to save it permanently.`)}}
  const share=async()=>{const url=new URL(location.href);url.searchParams.set('surfaces',selected.map(t=>t.id).join(','));url.searchParams.set('walls',wallStyles.map(s=>s.color).join(','));url.searchParams.set('patterns',wallStyles.map(s=>s.design).join(','));url.searchParams.set('room',String(room));try{await navigator.clipboard.writeText(url.toString());setNotice('Design link copied with every wall colour, finish and tile.')}catch{setNotice('Copy this design link from the address bar.');history.replaceState(null,'',url)}}
  const filtered=catalogTiles.filter(t=>(filter==='All'||t.family===filter)&&(!onlySaved||saved.includes(t.id))&&`${t.name} ${t.family} ${t.id}`.toLowerCase().includes(query.toLowerCase()))
  return <main className="app min-h-screen">
    <header className="topbar"><a className="brand" href="#" aria-label="MJP Ceramics home"><span className="brand-mark"><i/><i/><i/></span><span className="brand-wordmark">MJP <em>CERAMICS</em></span></a>
      <nav aria-label="Main navigation" className={menu?'open':''}><button className="active" onClick={()=>{document.getElementById('showroom')?.scrollIntoView({behavior:'smooth'});setMenu(false)}}>EXPLORE</button><button onClick={()=>openCatalog()}>COLLECTIONS</button><button onClick={()=>{setModal('inspiration');setMenu(false)}}>INSPIRATION</button><button onClick={()=>{document.getElementById('journal')?.scrollIntoView({behavior:'smooth'});setMenu(false)}}>JOURNAL</button><button onClick={()=>{document.getElementById('contact')?.scrollIntoView({behavior:'smooth'});setMenu(false)}}>CONTACT</button></nav>
      <div className="head-actions"><button className="search" onClick={()=>openCatalog()}><Search size={18}/><span>Find your surface</span></button><button className="icon-btn favorites-header" aria-label={`Saved tiles, ${saved.length}`} onClick={()=>openCatalog(true)}><Heart size={18}/>{saved.length>0&&<span>{saved.length}</span>}</button><button className="menu-btn" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu size={22}/></button></div>
    </header>
    <section id="showroom" className={`viewer live-viewer ${walking?'is-walking':''} ${stereo?'is-stereo':''} ${paintOpen?'paint-open':''} ${quickPaint?'quick-paint-open':''}`} aria-label="3D tile showroom">
      <Walkthrough ref={view} selected={selected} wallStyles={wallStyles} walking={walking} stereo={stereo} brightness={brightness} onRoom={setRoom} onWallPick={id=>{setActiveWall(id);setPaintOpen(false);setQuickPaint(true)}} onWalking={setWalking} onNotice={setNotice} onReady={()=>setReady(true)} onXR={setXR}/>
      {!ready&&<div className="loading-view" role="status"><span className="loading-orbit"/>Opening your residence…</div>}
      {!walking&&!stereo&&<div className="title-block"><p className="eyebrow"><span/> MJP CERAMICS / THE LIVE DESIGN STUDIO</p><h1>Make room for<br/><i>your vision.</i></h1><p className="subcopy">Choose the tile. Paint the walls.<br/>Walk through a home that feels like yours.</p><button className="enter-button" disabled={!ready} onClick={()=>view.current?.enter()}><Footprints size={17}/> STEP INSIDE <MoveRight size={18}/></button><small className="drag-hint">Or drag the room to look around</small></div>}
      <div className="mode-switch"><button className={!stereo?'selected':''} onClick={()=>setStereo(false)}><Eye size={15}/> Normal view</button><button className={stereo?'selected':''} onClick={()=>setModal('vr')}><span className="headset-icon" aria-hidden="true">◉◉</span> VR mode</button></div>
      <div className="view-tools"><button title="Customise wall colours" aria-label="Customise wall colours" aria-expanded={paintOpen} className={paintOpen?'tool-active':''} onClick={()=>{if(document.pointerLockElement)document.exitPointerLock();if(!paintOpen)setActiveWall(room*4);setQuickPaint(false);setPaintOpen(!paintOpen)}}><Paintbrush size={18}/></button><button title="How to explore" aria-label="Walkthrough instructions" onClick={()=>setModal('guide')}><Footprints size={18}/></button><button title="Fullscreen" aria-label="Toggle fullscreen" onClick={()=>view.current?.fullscreen()}><Expand size={18}/></button><button title="Share your design" aria-label="Copy design link" onClick={()=>void share()}><Share2 size={18}/></button></div>
      {quickPaint&&<div className="wall-quickbar" aria-label="Selected wall quick colours and designs"><div className="quickbar-top"><span><Paintbrush size={14}/> {roomNames[Math.floor(activeWall/4)]} / {wallSides[activeWall%4]}</span><button aria-label="Close wall colours" onClick={()=>setQuickPaint(false)}><X size={15}/></button></div><div className="quick-colours">{paintSwatches.map(s=><button key={s.color} className={wallStyles[activeWall].color.toLowerCase()===s.color?'active':''} title={s.name} aria-label={`${s.name} wall colour`} aria-pressed={wallStyles[activeWall].color.toLowerCase()===s.color} style={{backgroundColor:s.color}} onClick={()=>styleWall({color:s.color})}/>) }<label className="quick-custom" title="Custom wall colour"><input type="color" aria-label="Custom selected wall colour" value={wallStyles[activeWall].color} onChange={e=>styleWall({color:e.target.value})}/><Paintbrush size={14}/></label></div><div className="quick-designs" aria-label="Selected wall design">{wallDesigns.map(design=><button key={design} aria-pressed={wallStyles[activeWall].design===design} className={wallStyles[activeWall].design===design?'active':''} onClick={()=>styleWall({design})}>{finishNames[design]}</button>)}</div></div>}
      {paintOpen&&<div className="paint-panel" aria-label="Wall colour studio"><div className="paint-panel-heading"><span>01 / WALL STUDIO</span><button aria-label="Close wall colour studio" onClick={()=>setPaintOpen(false)}><X size={17}/></button></div><h2>Make every wall yours.</h2><p>Click a wall in the 3D home, or select it below. Colour and design apply only to that wall.</p><div className="paint-rooms" aria-label="Choose room to paint">{roomNames.map((name,i)=><button key={name} className={Math.floor(activeWall/4)===i?'active':''} aria-pressed={Math.floor(activeWall/4)===i} onClick={()=>jump(i)}>{name}</button>)}</div><div className="wall-selector" aria-label="Choose an individual wall">{wallSides.map((side,i)=><button key={side} className={activeWall%4===i?'active':''} aria-pressed={activeWall%4===i} onClick={()=>setActiveWall(Math.floor(activeWall/4)*4+i)}>{side}</button>)}</div><span className="paint-section-label">COLOUR / {roomNames[Math.floor(activeWall/4)].toUpperCase()} · {wallSides[activeWall%4].toUpperCase()}</span><div className="paint-swatches" aria-label="Wall colour presets">{paintSwatches.map(s=><button key={s.color} title={s.name} aria-label={`${s.name} wall colour`} aria-pressed={wallStyles[activeWall].color.toLowerCase()===s.color} style={{backgroundColor:s.color}} onClick={()=>styleWall({color:s.color})}>{wallStyles[activeWall].color.toLowerCase()===s.color&&<Check size={14}/>}</button>)}</div><label className="custom-paint"><span><Paintbrush size={15}/> CUSTOM COLOUR</span><input type="color" aria-label={`Custom wall colour for ${roomNames[Math.floor(activeWall/4)]} ${wallSides[activeWall%4]}`} value={wallStyles[activeWall].color} onChange={e=>styleWall({color:e.target.value})}/><b>{wallStyles[activeWall].color.toUpperCase()}</b></label><span className="paint-section-label design-label">20 DESIGNS / WALL TILE & FINISH</span><div className="wall-finishes" aria-label="20 wall tile and finish options">{wallDesigns.map(design=><button key={design} className={`finish-option finish-${design} ${wallStyles[activeWall].design===design?'active':''}`} aria-pressed={wallStyles[activeWall].design===design} onClick={()=>styleWall({design})}><span aria-hidden="true"/><b>{finishNames[design]}</b></button>)}</div><button className="reset-paint" onClick={()=>styleWall({color:defaultWalls[Math.floor(activeWall/4)],design:'paint'})}>Reset selected wall</button></div>}
      <div className="scene-status"><span/> LIVE 3D <i/> {roomNames[room]}</div>
      {walking&&<button className="exit-walk" onClick={()=>setWalking(false)}><X size={15}/> Exit walkthrough</button>}
      <div className="room-nav"><p>EXPLORE THE HOME <span className="room-nav-note">/ SELECT A ROOM OR WALK THROUGH</span></p><div>{roomNames.map((name,i)=><button key={name} className={room===i?'current':''} aria-pressed={room===i} onClick={()=>jump(i)}><span className="room-number">0{i+1}</span><span>{name}</span></button>)}</div></div>
      <label className="daylight-control"><Sun size={16}/><span>DAYLIGHT</span><input type="range" aria-label="Room brightness" min="0.55" max="1.45" step="0.05" value={brightness} onChange={e=>setBrightness(Number(e.target.value))}/></label>
    </section>
    <section className="selection-panel">
      <button className="add-design-button collection-upload-trigger" onClick={()=>setModal('upload')}><Upload size={15}/> ADD YOUR DESIGN</button>
      <div className="collection-title"><p>CURATED FOR YOUR HOME</p><h2>Made for <i>moments</i><br/>that matter.</h2><button className="all-tiles" onClick={()=>openCatalog()}>EXPLORE ALL 30 SURFACES <MoveRight size={17}/></button><div className="material-dots">{tiles.slice(0,7).map(t=><button key={t.id} aria-label={`Apply ${t.name}`} aria-pressed={t.id===tile.id} onClick={()=>apply(t)} style={{backgroundImage:`url(${sampleUrl(t)})`}}/>)}<button className="more-dots" aria-label="Show all tile designs" onClick={()=>openCatalog()}>+23</button></div></div>
      <div className="tile-stage"><button className="tile-swatch real-swatch" style={{backgroundImage:`url(${sampleUrl(tile)})`}} aria-label={`View ${tile.name} details`} onClick={()=>setModal('details')}><span>MJP CERAMICS / {tile.id}</span><ArrowUpRight size={18}/></button><div className="tile-arrows"><button aria-label="Previous tile" onClick={()=>apply(tiles[(current+tiles.length-1)%tiles.length])}><ChevronLeft size={22}/></button><span>{String(current+1).padStart(2,'0')} <i>/</i> 30</span><button aria-label="Next tile" onClick={()=>apply(tiles[(current+1)%tiles.length])}><ChevronRight size={22}/></button></div></div>
      <div className="product-info"><div className="product-heading"><p>YOUR SELECTED SURFACE</p><h3>{tile.name}</h3><span>{tile.id} · {tile.size}</span></div><p className="description">{tile.family} inspired porcelain. A {tile.finish.toLowerCase()} finish, considered in every detail. See this surface at scale as you move through your home.</p><label className="apply-scope">APPLY TO <select aria-label="Tile application scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Whole house</option><option value="room">Current room only</option></select></label><div className="info-footer"><button className="details" onClick={()=>setModal('details')}>SURFACE DETAILS <MoveRight size={16}/></button><button className={isLiked?'heart liked':'heart'} aria-label={isLiked?'Unsave selected tile':'Save selected tile'} aria-pressed={isLiked} onClick={()=>toggleSave(tile.id)}><Heart fill={isLiked?'currentColor':'none'} size={20}/></button></div><p className="applied-note" aria-live="polite"><Check size={12}/>{applied||'Surface applied throughout the residence'}</p></div>
    </section>
    <section id="journal" className="journal-section"><div className="section-intro"><p>MJP CERAMICS / DESIGN JOURNAL</p><h2>Ideas for a home<br/><i>made personal.</i></h2><span>Practical material guidance, colour pairings and thoughtful ways to use tile.</span></div><div className="journal-grid">{articles.map((item,index)=><article key={item.id} className={index===0?'featured':''}><button className="journal-image" onClick={()=>{setArticleId(item.id);setModal('blog')}}><img src={item.image} alt={item.imageAlt} loading="lazy"/><span>{item.category}</span></button><div><small>{item.readTime}</small><h3>{item.title}</h3><p>{item.excerpt}</p><button className="read-article" onClick={()=>{setArticleId(item.id);setModal('blog')}}>READ STORY <ArrowUpRight size={15}/></button></div></article>)}</div></section>
    <section id="contact" className="contact-section"><div className="contact-copy"><p>VISIT MJP CERAMICS</p><h2>Let’s shape your<br/><i>space together.</i></h2><span>Bring your room measurements, ideas or saved MJP Ceramics design. Our material studio can help you move from screen to sample.</span></div><div className="contact-details"><a href="tel:+919000000000"><Phone size={18}/><span><small>CALL / WHATSAPP — DEMO</small>+91 90000 00000</span></a><a href="mailto:hello@mjpceramics.example"><Mail size={18}/><span><small>EMAIL — DEMO</small>hello@mjpceramics.example</span></a><div><MapPin size={18}/><span><small>SHOWROOM</small>Shri Erumbeeswarar Temple, State Highway 49, Malaikoil, Thiruverumbur, Tamil Nadu 620013</span></div><div><Clock3 size={18}/><span><small>OPENING HOURS — DEMO</small>Mon–Sat · 9:30 AM–7:30 PM</span></div></div><form className="contact-form" onSubmit={e=>{e.preventDefault();setNotice('Demo enquiry form ready. Connect your email or CRM before launch.')}}><label>NAME<input required name="name" placeholder="Your name"/></label><label>PHONE / EMAIL<input required name="contact" placeholder="How can we reach you?"/></label><label className="full-field">YOUR PROJECT<textarea name="message" rows={3} placeholder="Tell us about the rooms and surfaces you are considering"/></label><button className="dark-button" type="submit">SEND DEMO ENQUIRY <MoveRight size={16}/></button></form></section>
    <section className="bottom-strip"><div><Grid2X2 size={18}/><span><b>30</b> CURATED SURFACES</span></div><div><Sparkles size={18}/><span>REAL-TIME <b>MATERIALS</b></span></div><div><Home size={18}/><span><b>4</b> CONNECTED ROOMS</span></div><button onClick={()=>{document.getElementById('showroom')?.scrollIntoView({behavior:'smooth'});view.current?.enter()}}>WALK THROUGH YOUR HOME <MoveRight size={17}/></button><a className="asset-credit" href="/ASSET_CREDITS.txt" target="_blank" rel="noreferrer">3D asset credit</a></section>
    {notice&&<div className="toast" role="status"><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    {modal==='collections'&&<Modal title="Find your kind of beautiful." wide onClose={()=>setModal(null)}><div className="catalog-topline"><p>30 surfaces. Five collections. One home, made yours.</p><label>APPLY TO<select aria-label="Collection application scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Whole house</option><option value="room">{roomNames[room]} only</option></select></label></div><div className="catalog-search"><Search size={18}/><input aria-label="Search tile collections" placeholder="Search by name, material or code…" value={query} onChange={e=>setQuery(e.target.value)}/><button aria-pressed={onlySaved} className={onlySaved?'chosen':''} onClick={()=>setOnlySaved(!onlySaved)}><Heart size={16} fill={onlySaved?'currentColor':'none'}/> Saved ({saved.length})</button></div><div className="filter-row" aria-label="Material filters">{['All',...families].map(f=><button key={f} className={filter===f?'chosen':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}<span>{filtered.length} surfaces</span></div><div className="catalog-grid">{filtered.map(t=><article className={`catalog-card ${tile.id===t.id?'chosen':''}`} key={t.id}><button className="sample-select" aria-label={`Apply ${t.name}`} onClick={()=>apply(t)}><img src={sampleUrl(t)} alt={`${t.name} ${t.family.toLowerCase()} tile texture`} loading="lazy"/>{tile.id===t.id&&<span className="selected-badge"><Check size={13}/> APPLIED</span>}<span className="sample-action">APPLY IN YOUR HOME <MoveRight size={15}/></span></button><div className="card-caption"><button onClick={()=>apply(t)}><h3>{t.name}</h3><p>{t.family} · {t.finish}</p></button><button className="save-card" aria-label={`${saved.includes(t.id)?'Unsave':'Save'} ${t.name}`} aria-pressed={saved.includes(t.id)} onClick={()=>toggleSave(t.id)}><Heart size={17} fill={saved.includes(t.id)?'currentColor':'none'}/></button></div></article>)}</div>{filtered.length===0&&<div className="empty-state"><Search size={30}/><h3>No surfaces here yet.</h3><p>{onlySaved?'Save a tile with the heart icon, or explore the full collection.':'Try a different name or material.'}</p><button onClick={()=>{setQuery('');setFilter('All');setOnlySaved(false)}}>Show all surfaces</button></div>}<div className="catalog-bottom"><span aria-live="polite"><Check size={15}/> {applied||`${tile.name} is selected`}</span><button className="dark-button" onClick={()=>{setModal(null);setWalking(true);document.getElementById('showroom')?.scrollIntoView({behavior:'smooth'})}}>VIEW IN YOUR HOME <MoveRight size={16}/></button></div></Modal>}
    {modal==='details'&&<Modal title={tile.name} onClose={()=>setModal(null)}><img className="detail-image" src={sampleUrl(tile)} alt={`${tile.name} tile sample`}/><dl className="specs"><div><dt>Collection</dt><dd>{tile.family}</dd></div><div><dt>Finish</dt><dd>{tile.finish}</dd></div><div><dt>Dimensions</dt><dd>{tile.size}</dd></div><div><dt>Design reference</dt><dd>{tile.id}</dd></div></dl><p className="fine-print">Illustrative digital collection. Colour and finish on a screen can differ from a physical sample.</p><button className="dark-button full-width" onClick={()=>toggleSave(tile.id)}><Heart size={16} fill={isLiked?'currentColor':'none'}/>{isLiked?'REMOVE FROM SAVED':'SAVE THIS SURFACE'}</button></Modal>}
    {modal==='guide'&&<Modal title="Make yourself at home." onClose={()=>setModal(null)}><div className="guide-steps"><article><b>01</b><div><h3>Step inside</h3><p>Click Step inside, then use W/A/S/D or the arrow keys to walk. Move your mouse to look. Press Esc to release the mouse. You can also drag the view.</p></div></article><article><b>02</b><div><h3>Explore every room</h3><p>Walk through the open doorways or use the room buttons to jump directly. The floor plan shows where you are. On mobile, drag to look and hold the arrow buttons to move.</p></div></article><article><b>03</b><div><h3>Make it yours</h3><p>Open Collections and choose a surface. Apply it to the whole house or just your current room. Save favourites with the heart, or share a link to your design.</p></div></article></div><button className="dark-button full-width" onClick={()=>{setModal(null);view.current?.enter()}}>LET’S EXPLORE <MoveRight size={16}/></button></Modal>}
    {modal==='inspiration'&&<Modal title="A feeling for every home." onClose={()=>setModal(null)}><p className="modal-description">Start with a considered palette. Each selection styles all four rooms, then you can make it your own.</p><div className="palette-list">{[{name:'The warm retreat',ids:[0,4,5,13],text:'Sand, natural oak and soft limestone.'},{name:'Quietly contemporary',ids:[2,12,20,16],text:'White marble, silver stone and pale birch.'},{name:'Colour with character',ids:[3,24,22,9],text:'Sage terrazzo, Riviera blue and deep green.'}].map(p=><button key={p.name} onClick={()=>{setSelected(p.ids.map(i=>tiles[i]));setApplied(`${p.name} applied across four rooms`);setModal(null)}}><div className="palette-swatches">{p.ids.map(i=><img src={sampleUrl(tiles[i])} key={i} alt={tiles[i].name}/>)}</div><h3>{p.name} <ArrowUpRight size={18}/></h3><p>{p.text}</p></button>)}</div></Modal>}
    {modal==='vr'&&<Modal title="Another way to be there." onClose={()=>setModal(null)}><p className="modal-description">Explore this same 3D residence through a compatible VR headset, or preview the two eye views on your screen.</p><div className="vr-options"><button onClick={()=>{setModal(null);void view.current?.enterVR()}}><span className="headset-icon">◉◉</span><div><h3>{xr?'Exit headset VR':'Enter headset VR'}</h3><p>WebXR headset · HTTPS or localhost required</p></div><ArrowUpRight size={20}/></button><button onClick={()=>{setStereo(!stereo);setWalking(true);setModal(null)}}><Eye size={25}/><div><h3>{stereo?'Exit stereo preview':'Stereo preview'}</h3><p>Two eye views · drag to look · screen preview only</p></div><ArrowUpRight size={20}/></button></div><p className="fine-print">In headset: left thumbstick to move, right thumbstick to turn. Point a controller at a clear floor area and press its trigger to teleport. Your headset’s system menu exits VR.</p></Modal>}
    {modal==='blog'&&<Modal title={article.title} wide onClose={()=>setModal(null)}><div className="article-layout"><img src={article.image} alt={article.imageAlt}/><article><div className="article-meta">{article.category} · {article.readTime}</div><p className="article-lead">{article.excerpt}</p>{article.sections.map(section=><section key={section.heading}><h3>{section.heading}</h3><p>{section.body}</p></section>)}<p className="fine-print">Digital previews are for visual planning. Always check the final product’s physical sample, technical data and suitability with your tile supplier.</p></article></div></Modal>}
    {modal==='upload'&&<Modal title="Add your tile design." onClose={()=>setModal('collections')}><form className="upload-design-form" onSubmit={e=>{e.preventDefault();addDesign()}}><p>Upload a seamless JPG, PNG or WebP texture. Maximum 5 MB. Choose whether it is for the floor, wall or both.</p><label className="upload-dropzone"><input aria-label="Upload tile texture image" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>readUpload(e.target.files?.[0])}/>{uploadImage?<img src={uploadImage} alt="Your uploaded tile texture preview"/>:<><Upload size={24}/><b>CHOOSE TEXTURE IMAGE</b><small>JPG · PNG · WebP · up to 5 MB</small></>}</label><div className="upload-fields"><label>TILE CODE<input aria-label="Custom tile code" required value={uploadCode} onChange={e=>setUploadCode(e.target.value.toUpperCase())} placeholder="Example: AT-W-1001"/></label><label>DESIGN NAME<input aria-label="Custom tile design name" required value={uploadName} onChange={e=>setUploadName(e.target.value)} placeholder="Example: Ocean Blue KitKat"/></label></div><div className="upload-fields"><label>COLLECTION<select aria-label="Custom tile family" value={uploadFamily} onChange={e=>setUploadFamily(e.target.value as Family)}>{families.map(f=><option key={f}>{f}</option>)}</select></label><label>FINISH<input aria-label="Custom tile finish" value={uploadFinish} onChange={e=>setUploadFinish(e.target.value)} placeholder="Matt / Polished"/></label></div><fieldset><legend>USE THIS DESIGN ON</legend>{(['Floor','Wall','Both'] as SurfaceUse[]).map(value=><label key={value}><input type="radio" name="surface" checked={uploadSurface===value} onChange={()=>setUploadSurface(value)}/>{value}</label>)}</fieldset><button className="dark-button full-width" type="submit"><Upload size={16}/> ADD TO COLLECTION</button></form></Modal>}
  </main>
}
createRoot(document.getElementById('root')!).render(<App/> )
